#!/bin/sh

### validate for formatting

exts="\.\(clj\|cljs\|cljc\|edn\)$"
formatter=$(which cljstyle)
# Check availability of the formatter
if [ -z "$formatter" ]
then
  1>&2 echo "$formatter not found. Pre-commit formatting will not be done."
  exit 0
fi

# Format staged files, ACMR is Added, Copied, Modifier, Renamed. See `man git-diff`
for file in $(git diff --cached --name-only --diff-filter=ACMR | grep $exts)
do
  echo "Formatting $file"
  # Get the file from index
  tmp_name="${file%%.*}.tmp.${file#*.}"
  git show ":$file"
  git show ":$file" > "$tmp_name"
  # Format it
  "$formatter" fix --report "$tmp_name"
  "$formatter" fix --report "$file"
  # Create a blob object from the formatted file
  hash=$(git hash-object -w "$tmp_name")
  # Add it back to index
  git update-index --add --cacheinfo 100644 "$hash" "$file"
  git diff HEAD "$file"
  # Remove the tmp file
  rm "$tmp_name"
done

# If no files left in index after formatting - fail
if [ ! "$(git diff --cached --name-only)" ]; then
  1>&2 echo "No files left after formatting"
fi