name: New issue for Reproducible Bug
description: "If you're sure it's reproducible: submit an issue so we can investigate."
labels: [bug]
body:
  - type: textarea
    attributes:
      render: shell
      label: "`bb config` output"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      render: markdown
      label: Step-by-step reproduction instructions
      value: |
        **Steps to reproduce the problem:**

        1. Step 1 (include the names of affected modules)
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
