blank_issues_enabled: false

contact_links:
  - name: Get help in our Slack Channel
    url: https://clojurians.slack.com/messages/clojure-garden
    about: Do you have a question? The fastest way to get help is on Clojure Garden's Slack channel!

