version: "3.9"
services:

  frontend:
    image: ghcr.io/clojure-garden/frontend:latest
    container_name: "frontend"
    hostname: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - garden-net


  backend:
    image: ghcr.io/clojure-garden/backend:latest
    container_name: "backend"
    hostname: backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DATABASE_NAME: ${BACKEND_PG_DATABASE_NAME}
      DATABASE_PORT: 5432
      DATABASE_USER: ${BACKEND_PG_USER}
      DATABASE_PASSWORD: ${BACKEND_PG_PASSWORD}
      DATABASE_HOST: backend-db
      GITHUB_OAUTH_TOKEN: ${BACKEND_GITHUB_OAUTH_TOKEN}
      TWITTER_OAUTH_TOKEN: ${BACKEND_TWITTER_OAUTH_TOKEN}
      SLACK_OAUTH_TOKEN_USER: ${BACKEND_SLACK_OAUTH_TOKEN_USER}
      SLACK_OAUTH_TOKEN_BOT: ${BACKEND_SLACK_OAUTH_TOKEN_BOT}
    networks:
      - garden-net
    depends_on:
      - backend-db


  backend-db:
    image: postgres:13-alpine
    container_name: "backend-db"
    hostname: backend-db
    ports:
      - "${BACKEND_PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${BACKEND_PG_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_PG_USER}
      POSTGRES_PASSWORD: ${BACKEND_PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - metabase-net
      - garden-net
    volumes:
      - "./${BACKEND_PG_DATA}:/var/lib/postgresql/data"
      - "./${BACKEND_PG_DUMP}:/dump"


  metabase:
    image: metabase/metabase:v0.41.2
    container_name: "metabase"
    hostname: metabase
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_PG_DATABASE_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_PG_USER}
      MB_DB_PASS: ${METABASE_PG_PASSWORD}
      MB_DB_HOST: metabase-db
    networks:
      - metabase-net
    depends_on:
      - metabase-db
    volumes:
      - /dev/urandom:/dev/random:ro


  metabase-db:
    image: postgres:13-alpine
    container_name: "metabase-db"
    hostname: metabase-db
    ports:
      - "${METABASE_PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${METABASE_PG_DATABASE_NAME}
      POSTGRES_USER: ${METABASE_PG_USER}
      POSTGRES_PASSWORD: ${METABASE_PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - metabase-net
    volumes:
      - "./${METABASE_PG_DATA}:/var/lib/postgresql/data"
      - "./${METABASE_PG_DUMP}:/dump"


  nginx:
    image: umputun/nginx-le:latest
    container_name: "proxy"
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "9443:9443"
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
      - LE_EMAIL=hello@clojure.garden
      - LE_FQDN=clojure.garden
    depends_on:
      - "frontend"
      - "backend"
      - "metabase"
    networks:
      - metabase-net
      - garden-net
    volumes:
      - "./proxy/etc/ssl:/etc/nginx/ssl"
      - "./proxy/etc/service.conf:/etc/nginx/service.conf"


networks:
  metabase-net:
    driver: bridge
  garden-net:
    driver: bridge
