version: "3.9"
services:

  backend-db:
    image: postgres:13-alpine
    container_name: "backend-db"
    hostname: backend-db
    ports:
      - "${BACKEND_PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${BACKEND_PG_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_PG_USER}
      POSTGRES_PASSWORD: ${BACKEND_PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - metabase-net
      - garden-net
    volumes:
      - "./${BACKEND_PG_DATA}:/var/lib/postgresql/data"
      - "./${BACKEND_PG_DUMP}:/dump"


  metabase:
    image: metabase/metabase:v0.41.2
    container_name: "metabase"
    hostname: metabase
    ports:
      - "${METABASE_PORT}:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_PG_DATABASE_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_PG_USER}
      MB_DB_PASS: ${METABASE_PG_PASSWORD}
      MB_DB_HOST: metabase-db
    networks:
      - metabase-net
    depends_on:
      - metabase-db
    volumes:
      - /dev/urandom:/dev/random:ro


  metabase-db:
    image: postgres:13-alpine
    container_name: "metabase-db"
    hostname: metabase-db
    ports:
      - "${METABASE_PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${METABASE_PG_DATABASE_NAME}
      POSTGRES_USER: ${METABASE_PG_USER}
      POSTGRES_PASSWORD: ${METABASE_PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - metabase-net
    volumes:
      - "./${METABASE_PG_DATA}:/var/lib/postgresql/data"
      - "./${METABASE_PG_DUMP}:/dump"


networks:
  metabase-net:
    driver: bridge
  garden-net:
    driver: bridge
