name: Publish docker images

on:
  push:
    branches:
      - master


env:
  registry: ghcr.io
  backend_path: 'modules/backend'


jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '0.6.8'

      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.12.16'

      - name: Setup cljstyle
        uses: just-sultanov/setup-cljstyle@v1
        with:
          version: '0.15.0'

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

      - name: '[backend] Run linters'
        working-directory: ${{ env.backend_path }}
        run: bb lint


  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup environment variables
        run: >-
          echo 'CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}' >> $GITHUB_ENV;

      - name: Setup openjdk
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: latest

      - name: Setup babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '0.6.8'

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

      - name: '[backend] Run unit tests'
        working-directory: ${{ env.backend_path }}
        run: bb test:unit

      - name: '[backend] Upload coverage'
        run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f ./${{ env.backend_path }}/coverage/codecov.json


  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup openjdk
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: latest

      - name: Setup babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '0.6.8'

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build docker images
        run: bb build-images

      - name: Run push docker images
        run: bb push-images
